steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_DEDICATED_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_DEDICATED_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output_dedicated'
    id: Prepare dedicated server deploy
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
          gsutil cp -r output_dedicated/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_DEDICATED_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output_dedicated/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_DEDICATED_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output_dedicated/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply dedicated deploy
    # Dedicated server should be deployed first, otherwise when 
    # first deployed, nodejs servers will fail to use DNS to find
    # dedicated server 
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_APP_NAME: js-server
  _DEDICATED_K8S_APP_NAME: dedicated-js-server
  _K8S_NAMESPACE: default
  _GKE_CLUSTER: cluster-cogteach
  _OUTPUT_BUCKET_PATH: artifacts.main-composite-344506.appspot.com/deploy
  _K8S_LABELS: ''
  _GKE_LOCATION: us-central1-c
  _DOCKERFILE_DIR: 'javascript/'
  _DOCKERFILE_NAME: Dockerfile
  _K8S_YAML_PATH: deployment/js-deployment.yaml
  _DEDICATED_K8S_YAML_PATH: deployment/js-deployment-dedicated.yaml
  _IMAGE_NAME: gcr.io/main-composite-344506/javascript
  _K8S_ANNOTATIONS: gcb-trigger-id=063e8ad3-b15f-4817-be2c-b78568fd7838
tags:
  - gke-cloud-build-deploy
  - $_K8S_APP_NAME
